# Generated by Django 5.2.8 on 2025-11-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_event_slug_alter_newspost_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.AddField(
            model_name='newspost',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
