# Generated by Django 5.2.8 on 2025-11-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_event_description_alter_newspost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Notice' or 'Urgent'", max_length=200)),
                ('content', models.TextField(help_text='Keep this short (1-2 sentences) for the top bar.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
