# Generated by Django 5.2.8 on 2025-11-23 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General Enquiries'), ('admissions', 'Admissions'), ('safeguarding', 'Safeguarding'), ('volunteering', 'Volunteering')], max_length=50)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Album Topic')),
                ('cover_image', models.ImageField(upload_to='gallery/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Us'), ('admissions', 'Admissions')], max_length=50)),
                ('section_name', models.CharField(help_text="e.g. 'History', 'Values', 'Admissions Intro'", max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Use the rich text editor')),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_content/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_class', models.CharField(default='fas fa-star', help_text="FontAwesome class, e.g., 'fas fa-book'", max_length=50)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Al Jannah Academy', max_length=200)),
                ('tagline', models.CharField(default='A structured and well equipped academy...', max_length=255)),
                ('head_teacher_name', models.CharField(default='Nazish Naseer', max_length=100)),
                ('head_teacher_phone', models.CharField(default='077 83 469546', max_length=50)),
                ('admin_contact_name', models.CharField(default='Hanif', max_length=100)),
                ('admin_contact_phone', models.CharField(default='07985 786786', max_length=50)),
                ('email', models.EmailField(default='info@aljannahacademy.com', max_length=254)),
                ('address', models.TextField(default='Royal Lane, Uxbridge, UB8 3RF')),
                ('google_maps_embed', models.TextField(blank=True, help_text='Paste the iframe code here')),
                ('facebook_link', models.URLField(blank=True)),
                ('whatsapp_link', models.URLField(blank=True)),
                ('term_timings', models.CharField(default='Saturdays: 11:00 AM – 2:00 PM (Term Time Only)', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. Headteacher', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('child_info', models.CharField(blank=True, help_text="Optional: e.g. 'Mother of 2'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.galleryalbum')),
            ],
        ),
    ]
