# Generated by Django 5.2.8 on 2025-11-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='linkedin_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='x_link',
            field=models.URLField(blank=True, verbose_name='X (Twitter) Link'),
        ),
    ]
