# Generated by Django 5.2.8 on 2025-11-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='youtube_link',
            field=models.URLField(blank=True, verbose_name='YouTube Link'),
        ),
    ]
