# Generated by Django 5.2.8 on 2025-11-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfiguration_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image (approx 400x300px)', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(blank=True, default='fas fa-star', max_length=50),
        ),
    ]
