# Generated by Django 5.2.8 on 2025-11-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_image_alter_service_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Optional: FontAwesome icon class, e.g. 'fa-solid fa-book'", max_length=50),
        ),
    ]
