# Generated by Django 5.2.8 on 2025-11-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_service_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='calendar_sidebar_image',
            field=models.ImageField(blank=True, help_text='Upload a vertical portrait image to show on the right side of the calendar page.', null=True, upload_to='site_assets/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='term_timings',
            field=models.CharField(default='Saturdays: 11:00 AM - 2:00 PM (Term Time Only)', max_length=200),
        ),
    ]
