# Generated by Django 5.2.8 on 2025-11-24 11:19

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pagecontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Bio'),
        ),
    ]
