# Generated by Django 5.2.8 on 2025-11-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_staffmember_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='external_admission_embed_code',
            field=models.TextField(blank=True, help_text='Paste the Iframe/HTML code from Google Forms, JotForm, or Microsoft Forms here.', verbose_name='Third-Party Embed Code'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='use_external_admission_form',
            field=models.BooleanField(default=False, help_text='Check this to hide the built-in Django form and show the embedded form below instead.', verbose_name='Use Third-Party Admission Form?'),
        ),
    ]
