# Generated by Django 5.2.8 on 2025-11-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_siteconfiguration_external_admission_embed_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='admin_contact_email',
            field=models.EmailField(blank=True, default='hislam.aljannahacademy@gmail.com', max_length=254, verbose_name='Admissions Email'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='admin_contact_name',
            field=models.CharField(default='M Hanif Islam', max_length=100, verbose_name='Admissions Name'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='admin_contact_phone',
            field=models.CharField(default='07985 786786', max_length=50, verbose_name='Admissions Phone'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email',
            field=models.EmailField(default='aljannahacademy@gmail.com', max_length=254, verbose_name='Head Teacher / Main Email'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='head_teacher_name',
            field=models.CharField(default='Nazish Naseer', max_length=100, verbose_name='Head Teacher Name'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='head_teacher_phone',
            field=models.CharField(default='07783 469546', max_length=50, verbose_name='Head Teacher Phone'),
        ),
    ]
