# Generated by Django 5.2.8 on 2025-11-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_siteconfiguration_admin_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='external_admission_embed_code',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='external_admission_url',
            field=models.URLField(blank=True, help_text='Paste the full link here (e.g., https://app.joinin.online/...)', verbose_name='Third-Party Registration URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='use_external_admission_form',
            field=models.BooleanField(default=False, help_text="Check this to hide the built-in form and show a 'Register Now' button pointing to an external site.", verbose_name='Use Third-Party Link?'),
        ),
    ]
