# Generated by Django 5.2.8 on 2025-11-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_siteconfiguration_external_admission_embed_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('about', 'About Us'), ('admissions', 'Admissions'), ('syllabus', 'Syllabus')], max_length=50),
        ),
    ]
