# Generated by Django 5.2.8 on 2025-11-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pagecontent_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook_embed_code',
            field=models.TextField(blank=True, help_text='Go to https://developers.facebook.com/docs/plugins/page-plugin/, generate the IFrame code, and paste it here.', verbose_name='Facebook Page Plugin Code'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='featured_video_title',
            field=models.CharField(blank=True, default='About Al Jannah Academy', max_length=200, verbose_name='Featured Video Title'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='featured_video_url',
            field=models.URLField(blank=True, help_text='Paste the full YouTube URL (e.g., https://www.youtube.com/watch?v=...)', verbose_name='YouTube Video Link'),
        ),
    ]
