# Generated by Django 5.2.8 on 2025-11-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed info about the project')),
                ('contact_person', models.CharField(blank=True, help_text='e.g. Sister Nazish', max_length=100)),
                ('contact_number', models.CharField(blank=True, help_text='e.g. 07783...', max_length=50)),
                ('external_link', models.URLField(blank=True, help_text='Link to external site or fee PDF')),
                ('link_text', models.CharField(default='Click here for details', help_text='Text for the button', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
