# Generated by Django 5.2.8 on 2025-11-23 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, help_text='Optional end time', null=True)),
                ('activity', models.CharField(help_text="e.g. 'Islamic Studies' or 'Registration'", max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Class Schedule Item',
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Rich text content for the policy')),
                ('order', models.IntegerField(default=0, help_text='Order in which to display the policy')),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, default='Al Jannah Academy', max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('pdf_file', models.FileField(blank=True, help_text='Optional download link', null=True, upload_to='books/pdfs/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='academics.subject')),
            ],
        ),
    ]
