# Generated by Django 5.2.8 on 2025-11-23 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Level',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='subject',
            new_name='level',
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Optional free download link', null=True, upload_to='books/pdfs/'),
        ),
        migrations.CreateModel(
            name='PurchaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(help_text='e.g. Amazon, Waterstones, eBay', max_length=50)),
                ('url', models.URLField(help_text='Paste the full link here')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_links', to='academics.book')),
            ],
        ),
    ]
