# Generated by Django 5.2.8 on 2025-11-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_rename_subject_level_rename_subject_book_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
