# Generated by Django 5.2.8 on 2025-11-24 10:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_dailyschedule_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Policy Content'),
        ),
    ]
