# Generated by Django 5.2.8 on 2025-11-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_policy_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='Student Full Name')),
                ('student_class', models.CharField(choices=[('K', 'Kindergarten (K)'), ('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7')], max_length=10)),
                ('parent_name', models.CharField(max_length=200, verbose_name='Parent Full Name')),
                ('parent_mobile', models.CharField(max_length=20)),
                ('parent_email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('new', 'New student'), ('promoted', 'Promoted'), ('missing', 'Missing'), ('other', 'Other')], max_length=20)),
                ('other_reason_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='If other, please specify')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in £ (e.g. 17.00)', max_digits=6, null=True),
        ),
    ]
