# Generated by Django 5.2.8 on 2025-11-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_bookorder_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='selected_books',
            field=models.TextField(blank=True, help_text='List of books selected by the user (if Reason is Missing)', null=True),
        ),
    ]
